kind: Template
apiVersion: v1
metadata:
  name: ${NAME}
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the test
    generation: 1
    labels:
      app: ${GROUP_NAME}
    name: ${NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${GROUP_NAME}
      deploymentconfig: ${NAME}
    strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${GROUP_NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
          - env:
            - name: TERM
              value: xterm
            command:
              - watch
              - '-d'
              - 'for url in $(echo ${API_URL} | tr "," "\n"); do curl -vsSL ${API_BASE}/${url} -o /dev/null 2>&1; done;'
            image: ${OS_IMAGE}:${OS_TAG}
            imagePullPolicy: Always
            name: ${NAME}
            resources:
              limits:
                cpu: 150m
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 128Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
parameters:
- name: NAME
  displayName: Name to apply to objects in the template
  value: cap-eagle-test-run
  required: true
- name: GROUP_NAME
  displayName: Group Name
  description: The name to group all of the frontend objects defined in this template.
  value: cap-eagle-test
  required: true
- name: OS_IMAGE
  displayName: OS Image Name
  description: The source image.
  value: registry.access.redhat.com/rhel7/rhel
  required: true
- name: OS_TAG
  displayName: OS Image Tag
  description: The source tag of the os image.
  value: 7.5-433
  required: true
- name: API_BASE
  displayName: API Endpoint
  description: The api endpoint to test.
  value: url
  required: true
- name: API_URL
  displayName: API URL
  description: The api endpoint to test.
  value: a;b;c
  required: true
